apiVersion: v1
kind: Service
metadata:
  name: ai-ensemble
  namespace: ai-ensemble
spec:
  type: ClusterIP
  selector:
    app: ai-ensemble
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
