apiVersion: v1
kind: Service
metadata:
  name: ai-ensemble-web
  namespace: ai-ensemble
spec:
  type: ClusterIP
  selector:
    app: ai-ensemble-web
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
