"""Add retrieved_context to Discussion model

Revision ID: 3a05a68a2500
Revises: 
Create Date: 2026-07-08 22:13:28.762644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a05a68a2500'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussions', sa.Column('retrieved_context_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('encryption_salt', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('master_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'master_key_encrypted')
    op.drop_column('users', 'encryption_salt')
    op.drop_column('discussions', 'retrieved_context_encrypted')
    # ### end Alembic commands ###
