<script lang="ts">
  import { discussion } from "../stores/discussion.svelte";
  import { downloadFile } from "../utils/helpers";
  import Icon from "./Icon.svelte";

  let open = $state(false);
  let copied = $state(false);

  function toggle() {
    open = !open;
  }

  function close() {
    open = false;
  }

  async function copy() {
    await navigator.clipboard.writeText(discussion.buildTranscript());
    copied = true;
    setTimeout(() => (copied = false), 1500);
    close();
  }

  function downloadPdf() {
    window.print();
    close();
  }

  function downloadDoc() {
    const md = discussion.buildTranscript();
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>AI-Ensemble Discussion</title>
<style>body{font-family:Calibri,Segoe UI,Arial,sans-serif;line-height:1.5;padding:32px;color:#111}pre,code{white-space:pre-wrap;font-family:Consolas,monospace}h1{font-size:22px}h2{font-size:17px;color:#333;margin-top:24px}hr{border:none;border-top:1px solid #ccc}</style>
</head><body><pre>${md.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>
<p style="color:#999;font-size:11px;margin-top:32px">Generated by AI-Ensemble</p></body></html>`;
    downloadFile("ai-ensemble-discussion.doc", html, "application/msword");
    close();
  }
</script>

<div class="export-menu">
  <button
    class="btn btn-ghost btn-sm"
    onclick={toggle}
    aria-label="Export discussion"
    aria-haspopup="menu"
    aria-expanded={open}
  >
    <Icon name="download" size="sm" /> Export
  </button>

  {#if open}
    <div class="dropdown" role="menu">
      <button class="item" role="menuitem" onclick={copy}>
        <Icon name={copied ? "check" : "copy"} size="sm" />
        {copied ? "Copied" : "Copy transcript"}
      </button>
      <button class="item" role="menuitem" onclick={downloadPdf}>
        <Icon name="download" size="sm" /> Download PDF
      </button>
      <button class="item" role="menuitem" onclick={downloadDoc}>
        <Icon name="file" size="sm" /> Download DOC
      </button>
    </div>
    <div class="backdrop" role="presentation" onclick={close}></div>
  {/if}
</div>

<style>
  .export-menu {
    position: relative;
  }
  .dropdown {
    position: absolute;
    right: 0;
    top: calc(100% + 6px);
    min-width: 180px;
    background: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: var(--radius);
    box-shadow: var(--shadow-md);
    padding: 6px;
    z-index: 30;
  }
  .item {
    display: flex;
    align-items: center;
    gap: 8px;
    width: 100%;
    padding: 8px 10px;
    background: none;
    border: none;
    border-radius: var(--radius);
    color: var(--text-primary);
    font-size: 13px;
    text-align: left;
  }
  .item:hover {
    background: var(--bg-tertiary);
  }
  .backdrop {
    position: fixed;
    inset: 0;
    z-index: 20;
  }
</style>
